name: Prettier Check

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check code formatting with Prettier
      run: docker run --rm -v ${{ github.workspace }}:/code ghcr.io/php-cs-fixer/php-cs-fixer:3.48-php8.2 fix --dry-run --diff -- ./src
